In [1]:
%autosave 0

Autosave disabled


In [2]:
from IPython.core.display import HTML
#css_file = '../../../style/style03my.css'
css_file = '../../../style/style01.css'
HTML(open(css_file, "r").read())

>### [Sergio Rojas](http://prof.usb.ve/srojas)<br>
[Departamento de F&iacute;sica](http://www.fis.usb.ve/), [Universidad Sim&oacute;n Bol&iacute;var](http://www.usb.ve/), [Venezuela](http://es.wikipedia.org/wiki/Venezuela)

>#### Content under [Creative Commons Attribution license CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/), [code under MIT license (c)](http://en.wikipedia.org/wiki/MIT_License)2016-2017 Sergio Rojas (srojas@usb.ve).###

In [3]:
from IPython.display import HTML
from IPython.display import Image

In [4]:
#Image(filename='./img/ex_regression.png', width=720, height=720)

In [5]:
#HTML('<iframe src=https://en.wikipedia.org/wiki/Mathematical_optimization width=700 height=350></iframe>')

In [6]:
#Image(filename='./Volume_2_Video_2.1_figs/vol2_v21_0x_Jderivatives.png', width=720, height=720)

### The squared error cost function 

\begin{aligned}
        {\textbf h}(\mathbf{\theta}) = \theta_0 {\textbf X}_0 + \theta_1 {\textbf X}_1 + \theta_2 {\textbf X}_2 + \cdots + \theta_n {\textbf X}_n =       
%        
\begin{pmatrix} {\textbf X}_0 \; {\textbf X}_1 \; {\textbf X}_2 \; \cdots \; {\textbf X}_n \end{pmatrix}
        \begin{pmatrix}\theta_0 \\
                       \theta_1 \\
                       \theta_2 \\
                       \vdots \\
                       \theta_n \end{pmatrix}
        %
        \end{aligned}

\begin{aligned}
        J(\theta) &= \frac{1}{2m}\sum_{i=1}^m \left[ h^{(i)}(\theta)-y^{(i)}\right]^2 \\
                  &= \frac{1}{2m}\sum_{i=1}^m \left[ \theta_0 X_0^{(i)} + \theta_1 X_1^{(i)} + \theta_2 X_2^{(i)} + \cdots + \theta_n X_n^{(i)} - y^{(i)}\right]^2,
        \end{aligned}

\begin{aligned}
       X = 
        \begin{pmatrix}
               X_0^{(1)} \quad X_1^{(1)} \quad X_2^{(1)} \quad \cdots \quad X_n^{(1)} \\
               X_0^{(2)} \quad X_1^{(2)} \quad X_2^{(2)} \quad \cdots \quad X_n^{(2)} \\
               X_0^{(3)} \quad X_1^{(3)} \quad X_2^{(3)} \quad \cdots \quad X_n^{(3)} \\
                \vdots   \quad  \vdots   \quad \vdots    \quad \vdots \quad \vdots  \\
               X_0^{(m)} \quad X_1^{(m)} \quad X_2^{(m)} \quad \cdots \quad X_n^{(m)}
         \end{pmatrix}
\end{aligned}

##### Computing the J cost function

In [7]:
def JcostF(theta, X, y):
    #----
    # In this function it is computed the J squared error cost function
    # or the function to which the minimum is going to be found
    #
    # The input parameters are the data points defining the function
    #      
    #       X : as a column matrix 
    #       y : as a column vector
    #   theta : the parameters fitting the model
    #
    # Author: Sergio Rojas
    #----
    import numpy as np
    m = len(y) # number of training examples
    #
    h = np.dot(X,theta) # also: X.dot(theta)
    square = (h-y)**2
    J = 1.0/(2.0*m) * np.sum(square)
    #
    return J

### The Gradient Descent algorithm

\begin{aligned}
\theta_k = \theta_k - \alpha \frac{\partial J(\theta)}{\!\!\!\! \partial \theta_k}, 
\end{aligned}

##### Derivatives of the squared error cost function

\begin{aligned}
\begin{pmatrix} 
             \frac{\partial J(\theta)}{\!\!\!\! \partial \theta_0} \\ 
             \frac{\partial J(\theta)}{\!\!\!\! \partial \theta_1} \\
             \frac{\partial J(\theta)}{\!\!\!\! \partial \theta_2} \\ 
                        \vdots \\
             \frac{\partial J(\theta)}{\!\!\!\! \partial \theta_n} 
         \end{pmatrix} =
   \frac{1}{m}\left[ \mathbf{-X}^{\rm T} \mathbf y+ (\mathbf X^{\rm T} \mathbf X ){\boldsymbol{\theta}} \right]   =
   \frac{1}{m}\mathbf{X}^{\rm T} \left[ \mathbf X {\boldsymbol{\theta}} - \mathbf y  \right]
\end{aligned}

##### Our implementation of Gradient Descent

In [8]:
def GradientDescent(X, y, theta, alpha, MAX_ITERS=1000, tolerance = 1e-05 ):
    #----
    # In this function it is computed the gradient descent algorithm
    # that updates the thetas:
    #
    # The input parameters:
    #      
    #       X : as a column matrix 
    #       y : as a column vector
    #   theta : the parameters fitting the model
    #   alpha : the learning rate
    #  
    # Author: Sergio Rojas
    #----
    import numpy as np
    m = len(y) # number of training examples
    J = np.array([])
    tol = 1
    k = 0
    while (tol > tolerance) and (k <= MAX_ITERS):
        k = k + 1
        h = np.dot(X,theta)
        temp = np.dot(np.transpose(h-y),X)
        temp = np.transpose(temp)        
        oldtheta = theta
        theta = theta - (alpha/m)*temp
        tol = np.sum(np.abs(theta-oldtheta))        
        J = np.append( J, JcostF(theta, X, y) ) 
        #tol = np.abs( JcostF(oldtheta, X, y) - JcostF(theta, X, y) )
    if k >= MAX_ITERS:
      print('WARNING!!!')
      print('A number of {0} iterations (>= MAX_ITERS) was reached'.format(k))
      print('you might want rerun the code using the reported  values for theta. \n')
    else:
        print('\t Convergence was reached after {0} iterations. \n'.format(k))

    return theta, J

##### An example testing our implementation of Gradient Descent

In [9]:
import numpy as np

In [10]:
X = np.column_stack((np.ones(10), np.arange(10)))
y = np.arange(10)
print('X = \n',X)
print('y = ',y)

X = 
 [[ 1.  0.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]]
y =  [0 1 2 3 4 5 6 7 8 9]


In [11]:
theta0 = np.array([2.,2.]) # initial guess
th, J = GradientDescent(X, y, theta0, 0.05)
print('theta =',th)

	 Convergence was reached after 563 iterations. 

theta = [  5.99002573e-04   9.99904474e-01]


##### [Solving the problem using SciPy linear regression function](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.stats.linregress.html)

In [12]:
# check with scipy linear regression 
from scipy import stats
slope, intercept, rvalue, pvalue, stderror = stats.linregress(X[:,1], y)
print ( ('intercept = {0} slope = {1}').format(intercept, slope) )

intercept = 0.0 slope = 1.0


##### [Solving the problem using SciPy optimize functions](https://docs.scipy.org/doc/scipy-0.18.1/reference/optimize.html)

In [13]:
from scipy import optimize
optimize.fmin_cg(JcostF, x0=[2, 2],args=(X,y))

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 2
         Function evaluations: 20
         Gradient evaluations: 5


array([  7.93900408e-08,   9.99999988e-01])

In [14]:
optimize.minimize(JcostF, x0=[2, 2],args=(X,y), method='CG', jac=False)

     fun: 9.261894271726636e-16
     jac: array([  3.48835160e-08,   2.40535063e-07])
 message: 'Optimization terminated successfully.'
    nfev: 20
     nit: 2
    njev: 5
  status: 0
 success: True
       x: array([  7.93900408e-08,   9.99999988e-01])

In [15]:
optimize.fmin_l_bfgs_b(JcostF, x0=[2, 2],args=(X,y),approx_grad=1 )

(array([ -8.13233676e-07,   1.00000012e+00]),
 9.594604562818161e-14,
 {'funcalls': 30,
  'grad': array([ -2.48270185e-07,   2.93838812e-08]),
  'nit': 7,
  'task': b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL',
  'warnflag': 0})

In [16]:
optimize.minimize(JcostF, x0=[2, 2],args=(X,y), method='L-BFGS-B', jac=False)

      fun: 9.594604562818161e-14
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
      jac: array([ -2.48270185e-07,   2.93838812e-08])
  message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 30
      nit: 7
   status: 0
  success: True
        x: array([ -8.13233676e-07,   1.00000012e+00])

### <font color=red>References</font> #

Additional discussion and examples can be found at:

- [Scipy Lecture Notes: Mathematical optimization: finding minima of functions](http://www.scipy-lectures.org/advanced/mathematical_optimization/)
- [SciPy Cookbook: Optimization and fitting](http://scipy-cookbook.readthedocs.io/items/idx_optimization_and_fitting.html)
- [Differential Evolution](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.differential_evolution.html)

>#### Content under [Creative Commons Attribution license CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/), [code under MIT license (c)](http://en.wikipedia.org/wiki/MIT_License)2016-2017 Sergio Rojas (srojas@usb.ve). ###
