In [1]:
%autosave 0

Autosave disabled


In [2]:
from IPython.core.display import HTML
css_file = '../../../style/style03my.css'
HTML(open(css_file, "r").read())

>### [Sergio Rojas](http://prof.usb.ve/srojas)<br>
[Departamento de F&iacute;sica](http://www.fis.usb.ve/), [Universidad Sim&oacute;n Bol&iacute;var](http://www.usb.ve/), [Venezuela](http://es.wikipedia.org/wiki/Venezuela)

>#### Content under [Creative Commons Attribution license CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/), [code under MIT license (c)](http://en.wikipedia.org/wiki/MIT_License)2016-2017 Sergio Rojas (srojas@usb.ve).###

# <center> The NumPy <font color=red>matrix</font> object </center>

[From the documentation](http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html) [http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html] A [NumPy] matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as \* (matrix multiplication) and \*\* (matrix power). In practice, the matrix object is intended to facilitate linear algebra computations [ https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html ]. Thus, we should bear in mind that [NumPy arrays](http://www.scipy-lectures.org/intro/numpy/array_object.html) [http://www.scipy-lectures.org/intro/numpy/array_object.html] are the most general NumPy data objects.

To create a NumPy **matrix object,** after importing Numpy to the current Python session (i.e. import numpy as np), the **np.matrix()** operation returns a matrix from an array-like object or from a string of data.

In [3]:
import numpy as np

In [4]:
a = np.matrix('1 2 3; 4 5 6')
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [5]:
temp = np.array([ [1, 2, 3], [4, 5, 6] ])
print(temp)
print(type(temp))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
b = np.matrix(temp)
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrixlib.defmatrix.matrix'>


# <center> Some <font color=red>matrix</font> operations </center>

## ** Switching back and forth between array-like objects and matrix-like objects **

In [7]:
temp = np.asarray(b)
print(temp)
print(type(temp))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [8]:
temp = np.asmatrix(temp)
print(temp)
print(type(temp))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrixlib.defmatrix.matrix'>


## **Element-wise multiplication**

In [60]:
temp = np.multiply(a,b)
print(temp)

[[ 1  4  9]
 [16 25 36]]


## **Element-wise division**

In [61]:
temp = a/b
print(temp)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


## Taking the **transpose**

In [62]:
a.T

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [63]:
a.getT()

matrix([[1, 4],
        [2, 5],
        [3, 6]])

## Matrix multiplication

In [64]:
temp = a*a.T
print(temp)

[[14 32]
 [32 77]]


## Taking the **inverse**

In [65]:
temp = a*a.T
print(temp)

[[14 32]
 [32 77]]


In [66]:
temp.I

matrix([[ 1.42592593, -0.59259259],
        [-0.59259259,  0.25925926]])

In [67]:
temp.getI()

matrix([[ 1.42592593, -0.59259259],
        [-0.59259259,  0.25925926]])

In [68]:
temp.getI()*temp

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [69]:
temp*temp.getI()

matrix([[ 1.,  0.],
        [ 0.,  1.]])

### Taking the **[Pseudo-inverse](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.pinv.html)** (non-square matrix inverse)

In [70]:
a.getI()

matrix([[-0.94444444,  0.44444444],
        [-0.11111111,  0.11111111],
        [ 0.72222222, -0.22222222]])

In [71]:
a*a.getI()

matrix([[  1.00000000e+00,   2.22044605e-16],
        [  0.00000000e+00,   1.00000000e+00]])

### $$\mathbf{A}_\text{right} = \mathbf{A}^T(\mathbf{A}\mathbf{A}^T)^{-1}$$

In [72]:
temp=a*a.getT()
a.getT()*temp.getI()

matrix([[-0.94444444,  0.44444444],
        [-0.11111111,  0.11111111],
        [ 0.72222222, -0.22222222]])

In [73]:
np.linalg.pinv(a)

matrix([[-0.94444444,  0.44444444],
        [-0.11111111,  0.11111111],
        [ 0.72222222, -0.22222222]])

## Matrix power $$\textbf{A}^n = \textbf{A}*\textbf{A}*\cdots*\textbf{A}$$ ($\textbf{A}$ repeated $n$-times)

In [79]:
temp**3

matrix([[110264, 263264],
        [263264, 628565]])

In [81]:
temp*temp*temp - temp**3

matrix([[0, 0],
        [0, 0]])

### Additional readings

In [74]:
from IPython.display import HTML

In [82]:
HTML('<iframe src=http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html width=700 height=350></iframe>')

In [76]:
HTML('<iframe src=https://en.wikipedia.org/wiki/Inverse_element#Matrices width=700 height=350></iframe>')

>#### Content under [Creative Commons Attribution license CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/), [code under MIT license (c)](http://en.wikipedia.org/wiki/MIT_License)2016-2017 Sergio Rojas (srojas@usb.ve). ###
